---
title: "Watershed Data Exploration Tool"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
runtime: shiny
---
  
```{r global, include=FALSE}
# load necessary packages and data sets
library(shiny)
library(tidyverse)
library(flexdashboard)

wellNames = list('A5', 'A6', 'A7', 'D1', 'H4', 'I3', 'I6', 'I7', 'I8', 
                 'I9', 'JD01', 'JD02', 'JD03', 'JD04', 'JD05', 'JD06',
                 'JD07', 'JD08', 'JD10', 'JD11', 'JD12', 'JD13', 'JD14',
                 'JD15', 'JD16', 'JD17', 'JD18', 'JD19', 'JD20', 'JD21',
                 'JD22', 'JD23', 'JD24', 'JD25', 'JD26', 'JD27', 'JD28',
                 'JD29', 'JD30', 'JD31', 'K1', 'K10', 'K11', 'K12', 
                 'K1D', 'K4D', 'K4M', 'K4S', 'K5', 'K6D', 'K6S', 'K7D', 
                 'K7S', 'K8', 'K9', 'N1', 'N2', 'N3', 'N4', 'N5', 'O1', 
                 'O2', 'P1', 'P2', 'Q1', 'Q2', 'T1')

setwd("C:/Users/Eric Rosenthal/Documents/SeniorYear2/Cap_git/EI_Capstone_S20/Query_Group")
well_data <- read_csv("sept2011Data.csv")
precip_data <- read_csv("PrecipSnow_BarData.csv")
```

Column {.sidebar}
---------------------------------------------------------------------
  
Explore data from watershed 3 in Hubbard Brook.
  
```{r}
# Select multiple wells based on well names
selectInput("select_wells", "Select Well(s):", 
            choices = wellNames, multiple = TRUE)

# Select a date range
dateRangeInput("date_range", "Select Date Range:", start = "2010-07-01", 
               end = "2018-01-10", format = "mm/dd/yy")

# plots/refreshes data
actionButton("plot_btn", label = "Plot")


```

Column
----------------------------------------------------------------------
---
title: "Tabset Row"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---

Row {data-height=500}
-------------------------------------
   
### Discharge

```{r}
```   
Row {data-height=500}
-------------------------------------
### Precipitation
    
```{r}
# Updates the well input when plot button is clicked
final_datesP <- reactiveValues(x = NULL)

# Updates the date range input when plot button is clicked
observeEvent(input$plot_btn, {
  final_datesP$x <- c(input$date_range[1], input$date_range[2])
  })

# Changes date range if brushing is detected
observeEvent(input$P_dblclick, {
  brush <- input$p_brush
  if (!is.null(brush))
    final_datesP$x <- c(brush$xmin, brush$xmax)
  else
    final_datesP$x <- c(input$date_range[1], input$date_range[2])
})

plotOutput("precip_level", dblclick = "P_dblclick", 
           brush = brushOpts(id = "p_brush"))

# renders the plot
output$precip_level <- renderPlot({
  
  
  ggplot(precip_data, aes(fill = Type, y = Value, x = DATE)) + 
  geom_bar(position="stack", stat="identity") + 
    theme_classic() +
    coord_cartesian(xlim = as.POSIXct(final_datesP$x,coord_cartesian), expand = FALSE) #if you delete this line it will appear on the graph above

  

})
``` 


Row {data-height=1400}
-------------------------------------
    
### Well Depth
    
```{r}
# Updates the well input when plot button is clicked
wells <- eventReactive(input$plot_btn, {input$select_wells})

final_dates <- reactiveValues(x = NULL)

# Updates the date range input when plot button is clicked
observeEvent(input$plot_btn, {
  final_dates$x <- c(input$date_range[1], input$date_range[2])
  })

# Changes date range if brushing is detected
observeEvent(input$wl_dblclick, {
  brush <- input$wl_brush
  if (!is.null(brush))
    final_dates$x <- c(brush$xmin, brush$xmax)
  else
    final_dates$x <- c(input$date_range[1], input$date_range[2])
})

plotOutput("water_level", dblclick = "wl_dblclick", 
           brush = brushOpts(id = "wl_brush"))

# renders the plot
output$water_level <- renderPlot({
  
  # subsets the wells
  selected_well_data <- filter(well_data, Well == wells())
  
  ggplot(data = selected_well_data, mapping = aes(x = date, y = level, color = Well)) + 
    geom_line() + scale_y_reverse() + ylab("Water Levels (mm)") +
    xlab("Date") + theme_classic() +
    coord_cartesian(xlim = as.POSIXct(final_dates$x, origin = "1970-01-01"), expand = FALSE)
})
```