---
title: "Watershed Data Exploration Tool"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    orientation: rows
    source_code: embed
runtime: shiny
---
  
```{r global, include=FALSE}
# load necessary packages and data sets
library(shiny)
library(tidyverse)
library(grid)

wellNames = list('A5', 'A6', 'A7', 'D1', 'H4', 'I3', 'I6', 'I7', 'I8', 'I9',
                 'JD01', 'JD02', 'JD03', 'JD04', 'JD05', 'JD06', 'JD07', 'JD08', 
                 'JD10', 'JD11', 'JD12', 'JD13', 'JD14', 'JD15', 'JD16', 'JD17',
                 'JD18', 'JD19', 'JD20', 'JD21', 'JD22', 'JD23', 'JD24', 'JD25',
                 'JD26', 'JD27', 'JD28', 'JD29', 'JD30', 'JD31', 'K1', 'K10', 
                 'K11', 'K12', 'K1D', 'K4D', 'K4M', 'K4S', 'K5', 'K6D', 'K6S', 
                 'K7D', 'K7S', 'K8', 'K9', 'N1', 'N2', 'N3', 'N4', 'N5', 'O1', 
                 'O2', 'P1', 'P2', 'Q1', 'Q2', 'T1')

precip_data <- read_csv("PrecipSnow_BarData.csv")
well_data <- read_csv("sept2011Data.csv")
slope_asp_data <- read_csv("slope_aspect_well_data.csv")
hpu_data <- read_csv("hpuDataClean.csv")
discharge_data <- read_csv("CleanDischargeData_")
```

Column {.sidebar}
--------------------------------------------------------------------------------

If this text isn't here, the appGuide button sticks to the top. Like the margin 
is for some reason = 0. but yeah lets put a section title here or fix the margin
  
```{r}
#opens up a read me
actionButton("appGuide", "Instructions")

# make a slider widget for slope
sliderInput("slope", "Select a slope range", min = 3.963356, max = 28.42197,
            value = c(3.963356, 28.42197), ticks = TRUE, dragRange = TRUE)

# make a slider widget for aspect
sliderInput("aspect", "Select an aspect range", min = 0.055854, max = 344.6115,
            value = c(0.055854, 344.6115), ticks = TRUE, dragRange = TRUE)

# checkbox group input to select which HPU units they want to see
checkboxGroupInput("hpu", "Select desired HPU(s):", 
                   choices = unique(hpu_data$HPU), 
                   selected = unique(hpu_data$HPU))

#Identiy range of precip to highlight
sliderInput("Prange", "Range of Precip Values to Highlight", value = c(0, 150), 
            min = 0, max = 100)

# Select multiple wells based on well names
selectInput("select_wells", "Select Well(s):", choices = wellNames, 
            multiple = TRUE)

#check box that gives user option to select all the wells from the well list
checkboxInput("selectAllWellsBox", "Select all wells in well list", 
              value = FALSE, width = NULL)

# Select a date range
dateRangeInput("date_range", "Select Date Range:", start = "2010-07-01", 
               end = "2018-01-10", format = "mm/dd/yy")

# log option for discharge y-axis
checkboxInput(inputId = "log", label = "Log discharge y axis.", value = FALSE)

# slider for plot text size
sliderInput(inputId = "mag", "Plot text size.", min = 10, max = 24, value = 10)

# downloads filtered data
downloadButton("downloadData", "Download")

downloadHandler(
  filename = "Water_Level.csv",
  content = function(file) {
    write.csv(as.data.frame(shiny::reactiveValuesToList(subseted_data)), 
              file, row.names = FALSE)
  }
)
```

```{r}
final_dates <- reactiveValues(x = as.POSIXct(c(start = "2010-07-01", 
                                               end = "2018-01-10")))

subseted_data <- reactiveValues(x = NULL)

observeEvent(input$date_range, {
  final_dates$x <- as.POSIXct(c(input$date_range[1], input$date_range[2]))
  })
```

Row {data-height=250}
--------------------------------------------------------------------------------
 
### Precipitation Plot

```{r}
renderPlot({
  
  # Filters the date and mutates for highlighted section
  precip_trim <- precip_data %>% 
    filter(between(as.POSIXct(DATE), final_dates$x[1], final_dates$x[2])) %>% 
    mutate(Highlight = ifelse(
      Value >= input$Prange[1] & Value <= input$Prange[2], Value, NA
      ))
  
  # Recieves total precip value of precip for selected dates
  Ptotal <- round(sum(precip_trim$Value, na.rm = TRUE), 2)
  
  # Format how total precip will appear on the graph
  grob <- grobTree(textGrob(paste("Total Precip:", Ptotal, "mm"), x = 0.1, 
                            y = 0.1, hjust = 0, gp = gpar(col="black", 
                                                          fontsize = input$mag, 
                                                          fontface="italic")))
  
  # plots the graph
  ggplot(data = precip_trim, aes(fill = Type, y = Value, x = DATE)) +
    geom_bar(position = "stack", stat = "identity") + theme_classic() +
    geom_bar(aes(DATE, Highlight), fill = "blue", stat = "identity") +
    xlab(element_blank()) + ylab("Precip (mm)") + scale_y_reverse() +
    theme(text = element_text(size=input$mag)) + annotation_custom(grob) +
    theme(legend.position = "bottom")
})
```
  
Row {data-height=400}
--------------------------------------------------------------------------------

### Water Table Plot

```{r}
#changes wells in wells select input box if slope slider values change
observeEvent(input$slope, {
  updateSelectInput(session, input = "select_wells", label = NULL, 
                    choices = getWellList(input$slope[1], input$slope[2], 
                                          input$aspect[1], input$aspect[2], 
                                          input$hpu), selected = NULL)})

#changes wells in wells select input box if aspect slider values change
observeEvent(input$aspect, {
  updateSelectInput(session, input = "select_wells", label = NULL, 
                    choices = getWellList(input$slope[1], input$slope[2],
                                          input$aspect[1], input$aspect[2], 
                                          input$hpu), selected = NULL)})

#changes wells in wells select input box if HPU selected box values change
observeEvent(input$hpu, {
  updateSelectInput(session, input = "select_wells", label = NULL, 
                    choices = getWellList(input$slope[1], input$slope[2],
                                          input$aspect[1], input$aspect[2], 
                                          input$hpu))})


#provides functionality to check box that allows user to add all wells 
#currently in the wells list to the graph
observeEvent(input$selectAllWellsBox, {
  updateSelectInput(session, input = "select_wells", label = NULL, 
                    selected = if(input$selectAllWellsBox == TRUE) {
                      c(getWellList(input$slope[1], input$slope[2], 
                                    input$aspect[1], input$aspect[2], 
                                    input$hpu))})})

# observes for brushing
observeEvent(input$wl_dblclick, {
  brush <- input$wl_brush
  if (!is.null(brush))
    updateDateRangeInput(session, input = "date_range", label = NULL, 
                    end = as.POSIXct(brush$xmax, origin = '1970-01-01'),
                    start = as.POSIXct(brush$xmin, origin = '1970-01-01'))
  else
    final_dates$x <- as.POSIXct(c(input$date_range[1], input$date_range[2]))
})

plotOutput("water_level", dblclick = "wl_dblclick", 
           brush = brushOpts(id = "wl_brush"))

output$water_level <- renderPlot({
  
  # Error message if well names are empty
  validate(
      need(input$select_wells != "", label = "Well Names")
    )
  
  # subsets the well data by selected wells and date range
  selected_well_data <- well_data %>% filter(Well == input$select_wells) %>% 
    filter(between(date, final_dates$x[1], final_dates$x[2]))
  
  subseted_data$x <- selected_well_data
  
  ggplot(selected_well_data, aes(x = date, y = level, color = Well)) + 
    geom_line() + scale_y_reverse() + ylab("Water Table Depth (cm)") +
    xlab(element_blank()) + theme_classic() + 
    theme(text = element_text(size=input$mag)) + 
    theme(legend.position = "bottom")
})
```

Row {data-height=250}
--------------------------------------------------------------------------------

### Discharge Plot

```{r}
renderPlot({
  
  # Filters the dates
  discharge_trim <- discharge_data %>% filter(between(as.POSIXct(Date), 
                                                final_dates$x[1],
                                                final_dates$x[2]))
  
  d_plot <- ggplot(discharge_trim, mapping = aes(x = Date, y = Discharge_ls)) +
    geom_line() + theme_classic() + ylab("Discharge (ltr/sec)") + 
    xlab(element_blank()) + theme(text = element_text(size=input$mag))
  
  # Changes the y-axis to a log
  if(input$log) 
    d_plot <- d_plot + scale_y_log10() 
  
  d_plot
})
```

```{r}
# helper function for the narrowing down well names by slope and aspect. Takes 
# the min and max vals and uses slope_asp_data to get the updated well names.
getWellList <- function(minValSlope, maxValSlope, minValAsp, maxValAsp, 
                        hpuValsList) { 
  #makes list of wells that fit slope and aspect selected by the sliders
  saWells <- slope_asp_data %>% 
    filter(between(Slope,minValSlope, maxValSlope), 
           between(Aspect, minValAsp, maxValAsp)) %>% select(Well)
    
  #makes list of wells that fit HPU selected by user 
  hpuWells <- hpu_data %>% subset(HPU %in% hpuValsList) %>% select(Well)
    
  #makes list of wells that are in both the slope/aspect list and the HPU list
  combWells <- intersect(hpuWells, saWells)
    
  #returns filtered wells list
  return(t(combWells))
}

# Pop up box if user clicks "Show App User Guide"
# <br> creates a new line
#https://www.w3schools.com/tags/default.asp this link help you with html inside 
  observeEvent(input$appGuide, {
    showModal(modalDialog(
      title = "App Instructions:",
      HTML("type your stuff in here
          <br>    
           
           test new line"
      )
    ))
  })
```