---
title: "Watershed Data Exploration Tool"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
runtime: shiny
---
  
```{r global, include=FALSE}
# load necessary packages and data sets
library(shiny)
library(tidyverse)

wellNames = list('A5', 'A6', 'A7', 'D1', 'H4', 'I3', 'I6', 'I7', 'I8', 
                 'I9', 'JD01', 'JD02', 'JD03', 'JD04', 'JD05', 'JD06',
                 'JD07', 'JD08', 'JD10', 'JD11', 'JD12', 'JD13', 'JD14',
                 'JD15', 'JD16', 'JD17', 'JD18', 'JD19', 'JD20', 'JD21',
                 'JD22', 'JD23', 'JD24', 'JD25', 'JD26', 'JD27', 'JD28',
                 'JD29', 'JD30', 'JD31', 'K1', 'K10', 'K11', 'K12', 
                 'K1D', 'K4D', 'K4M', 'K4S', 'K5', 'K6D', 'K6S', 'K7D', 
                 'K7S', 'K8', 'K9', 'N1', 'N2', 'N3', 'N4', 'N5', 'O1', 
                 'O2', 'P1', 'P2', 'Q1', 'Q2', 'T1')

well_data <- read_csv("sept2011Data.csv")
slope_asp_data <- read_csv("slope_aspect_well_data.csv")
```

Column {.sidebar}
---------------------------------------------------------------------
  
Explore data from watershed 3 in Hubbard Brook.
  
```{r}
#allow user to choose well(s) by slope and or aspect
#determine min and max for slope data
minSlope <- min(slope_asp_data$Slope)
maxSlope <- max(slope_asp_data$Slope, na.rm = TRUE)

#make a slider widget for slope
sliderInput("slope", "Select a slope range", 
            min = minSlope, max = maxSlope,
            value = c(minSlope, maxSlope), ticks = TRUE, dragRange = TRUE)

#determine min and max for aspect data
minAsp <- min(slope_asp_data$Aspect)
maxAsp <- max(slope_asp_data$Aspect, na.rm = TRUE)

#make a slider widget for aspect
sliderInput("aspect", "Select an aspect range", 
            min = minAsp, max = maxAsp,
            value = c(minAsp, maxAsp), ticks = TRUE, dragRange = TRUE)

wellChoicesCol <- reactiveValues(x = NULL)
observeEvent(input$slope, {
  wellChoicesCol$x <- slope_asp_data %>% filter(Slope >= input$slope[1] && Slope <= input$slope[2]) %>% select(Well)})

# Select multiple wells based on well names
#selectInput("select_wells", "Select Well(s):", 
            #choices = wellNames, multiple = TRUE)
selectInput("select_wells", "Select Well(s):", 
            choices = wellChoicesCol, multiple = TRUE)

# Select a date range
dateRangeInput("date_range", "Select Date Range:", start = "2010-07-01", 
               end = "2018-01-10", format = "mm/dd/yy")


# plots/refreshes data
actionButton("plot_btn", label = "Plot")
```

Column
---------------------------------------------------------------------
  
### Water Level Plot

```{r}
# Updates the well input when plot button is clicked
wells <- eventReactive(input$plot_btn, {input$select_wells})

final_dates <- reactiveValues(x = NULL)

# Updates the date range input when plot button is clicked
observeEvent(input$plot_btn, {
  final_dates$x <- c(input$date_range[1], input$date_range[2])
  })

# Changes date range if brushing is detected
observeEvent(input$wl_dblclick, {
  brush <- input$wl_brush
  if (!is.null(brush))
    final_dates$x <- c(brush$xmin, brush$xmax)
  else
    final_dates$x <- c(input$date_range[1], input$date_range[2])
})

plotOutput("water_level", dblclick = "wl_dblclick", 
           brush = brushOpts(id = "wl_brush"))

#subsets wells by chosen slope and aspect ranges 
#slope_wells_col <- slope_asp_data %>% filter(Slope >= input$slope[1] && Slope <= input$slope[2]) %>% select(Well)
#wells <- c(slope_wells_col)
#renders the plot
output$water_level <- renderPlot({
  



#subsets the wells by well selection
  selected_well_data <- filter(well_data, Well == wells())

#plots selected wells' well water level data
  ggplot(data = selected_well_data, mapping = aes(x = date, y = level, color = Well)) + 
    geom_line() + scale_y_reverse() + ylab("Water Table Depth (cm)") +
    xlab("Date") + theme_classic() +
    coord_cartesian(xlim = as.POSIXct(final_dates$x, origin = "1970-01-01"), expand = FALSE)
})
```