---
title: "Well Water Data Cleaning"
author: "Erica Schermerhorn"
date: "2/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)

wellNames = list('A5', 'A6', 'A7', 'D1', 'H4', 'I3', 'I6', 'I7', 'I8', 'I9', 'JD01', 'JD02', 'JD03', 'JD04', 'JD05', 'JD06', 'JD07', 'JD08', 'JD10', 'JD11', 'JD12', 'JD13', 'JD14', 'JD15', 'JD16', 'JD17', 'JD18', 'JD19', 'JD20', 'JD21', 'JD22', 'JD23', 'JD24', 'JD25', 'JD26', 'JD27', 'JD28', 'JD29', 'JD30', 'JD31', 'K1', 'K10', 'K11', 'K12', 'K1D', 'K4D', 'K4M', 'K4S', 'K5', 'K6D', 'K6S', 'K7D', 'K7S', 'K8', 'K9', 'N1', 'N2', 'N3', 'N4', 'N5', 'O1', 'O2', 'P1', 'P2', 'Q1', 'Q2', 'T1')

#read in all csvs into a list, with each data table accessible by each well's name
wellDatasList <- list()
setwd("C:/Users/scint/OneDrive/Documents/VT/Spring 2020/capstone/WS3_waterlevel_data/")

#dirNames <- list.dirs(path = "C:/Users/scint/OneDrive/Documents/VT/Spring 2020/capstone/WS3_waterlevel_data/.", full.names = FALSE, recursive = TRUE)

for (well in wellNames){
  wellDatasList[[well]] <- read_csv(paste(well,"csv", sep = "."))
}
#read in well info csv
wellInfo <- read_csv("C:/Users/scint/OneDrive/Documents/VT/Spring 2020/capstone/w3well_locations.txt")
```

The code below reads in all the csv files containing the well data, then adds a column containing the well name and appends all the well's tibbles together into one big master tibble called allWellsData.
```{r}
#add the well name column for each well's data table
i <- 1
wellsWNamesList <- list()
for (well in wellDatasList){
  wellsWNamesList[[i]] <- well %>% mutate(Well = wellNames[[i]])
  i <- i + 1
}


#make one master data table with all the wells
allWellData <- do.call(rbind, wellsWNamesList)

#join well info to all well data
wellDataJoined <- left_join(allWellData, wellInfo, by = "Well")

#set values  > 168 to NA
wellDataJoined$level <- replace(wellDataJoined$level, wellDataJoined$level > 168, NA)

#replace -99 values with NA
wellDataJoined$level <-  na_if(wellDataJoined$level, -99)
  
#subtract pipe height from level
finalWellData <- wellDataJoined %>% mutate(level = level - PipeHt)

#make date a datetime type
finalWellData <- finalWellData %>% rename(date = date.) %>% mutate(date = ymd_hms(date))

#read in slope and aspect data for each well
allSlopeAspData <- read_csv("C:/Users/scint/OneDrive/Documents/VT/Spring 2020/capstone/EI_Capstone_S20/Map_Group/Well_location_data.csv")

write_csv(allSlopeAspData, "C:/Users/scint/OneDrive/Documents/VT/Spring 2020/capstone/EI_Capstone_S20/Query_Group/slope_aspect_well_data.csv")
#write_csv(finalWellData, "C:/Users/scint/OneDrive/Documents/VT/Spring 2020/capstone/cleanWellData2.csv")

sept2011WellData <- finalWellData %>% filter(date > "2011-08-31" & date < "2011-10-01")

write_csv(sept2011WellData, "C:/Users/scint/OneDrive/Documents/VT/Spring 2020/capstone/EI_Capstone_S20/Query_Group/sept2011Data.csv")

```


The code below reads in water chemistry data from weir and the water amount at the weir:
```{r}
#read in the water chemistry data
allWaterChemData <- read_csv("C:/Users/scint/OneDrive/Documents/VT/Spring 2020/capstone/waterChem.csv")

#filters water chemistry data
waterChemData <- allWaterChemData %>% mutate(Date = as.Date(Date, "%m/%d/%Y")) %>% mutate(Date = as.POSIXct(Date))

anAttempt <- waterChemData %>% group_by(Site)
anAttempt <- anAttempt[-c(0:9),]

#writes filtered data to csv
#write_csv(waterChemData, "C:/Users/scint/OneDrive/Documents/VT/Spring 2020/capstone/EI_Capstone_S20/Query_Group/waterChemData.csv")
  
allWeirEarlyData <- read_csv("C:/Users/scint/OneDrive/Documents/VT/Spring 2020/capstone/w3_stmflow_1957-2012.csv")
allWeirLaterData <- read_csv("C:/Users/scint/OneDrive/Documents/VT/Spring 2020/capstone/w3_stmflow_2013-2017_5min.csv")

#make sure that the columns from both tables match up
weirEarlyData <- allWeirEarlyData %>% drop_na(DATETIME)
weirLaterData <- allWeirLaterData %>% drop_na(DATETIME) %>% select(-Flag)

#add both tables together by column names
allWeirData <- rbind(weirEarlyData, weirLaterData) %>% drop_na() %>% filter(WS == 3)

#write_csv(allWeirData, "C:/Users/scint/OneDrive/Documents/VT/Spring 2020/capstone/EI_Capstone_S20/Query_Group/weirDischargeData.csv")

ggplot(allWeirData, aes(DATETIME, Gage_ft)) + geom_line() + labs(title = "Weir Gage Ft over time", x = "Date")
```


The code below reads in slope and aspect and elevation data at each well
```{r}
#read in csv file
allSlopeAspData <- read_csv("C:/Users/scint/OneDrive/Documents/VT/Spring 2020/capstone/EI_Capstone_S20/Map_Group/Well_location_data.csv")


```

